2021-08-03 16:55:18,855 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 16:55:35,941 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 16:56:02,677 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 16:56:02,677 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:353] - INFO: 成功开启流量代理服务器:('192.168.43.30', 22222)
等待客户端连接...
2021-08-03 16:56:52,899 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 16:57:22,504 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 16:57:39,211 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.30', 53276)与服务器连接成功
2021-08-03 16:57:39,211 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 16:58:48,950 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:284] - INFO: 正在请求：('192.168.43.30', 53276)请求目的ip:('192.168.43.30', 11111)
2021-08-03 16:58:48,950 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:54] - INFO: 请求成功：('192.168.43.30', 53276)正在与('192.168.43.30', 11111)通讯...

2021-08-03 16:59:51,964 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.30', 53276)正在给('192.168.43.30', 11111)发送信息
2021-08-03 16:59:52,060 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.30', 53276)的回复：

Windows IP 配置


以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 本地连接* 11:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::c84d:500a:2b62:d8a7%14
   IPv4 地址 . . . . . . . . . . . . : 192.168.152.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::9860:7c4:58bb:99be%18
   IPv4 地址 . . . . . . . . . . . . : 192.168.157.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::28af:2f50:18fd:407%10
   IPv4 地址 . . . . . . . . . . . . : 192.168.43.30
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.43.1

2021-08-03 16:59:52,060 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.30', 53276)发送回复：

Windows IP 配置


以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 本地连接* 11:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::c84d:500a:2b62:d8a7%14
   IPv4 地址 . . . . . . . . . . . . : 192.168.152.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::9860:7c4:58bb:99be%18
   IPv4 地址 . . . . . . . . . . . . : 192.168.157.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::28af:2f50:18fd:407%10
   IPv4 地址 . . . . . . . . . . . . : 192.168.43.30
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.43.1

2021-08-03 17:01:48,224 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 17:01:48,258 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 17:01:48,268 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:353] - INFO: 成功开启流量代理服务器:('192.168.43.30', 22222)
等待客户端连接...
2021-08-03 17:01:50,073 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.30', 53301)与服务器连接成功
2021-08-03 17:01:50,073 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 17:02:00,416 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:284] - INFO: 正在请求：('192.168.43.30', 53301)请求目的ip:('192.168.43.30', 11111)
2021-08-03 17:02:00,416 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:54] - INFO: 请求成功：('192.168.43.30', 53301)正在与('192.168.43.30', 11111)通讯...

2021-08-03 17:02:08,738 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.30', 53301)正在给('192.168.43.30', 11111)发送信息
2021-08-03 17:02:08,831 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.30', 53301)的回复

2021-08-03 17:02:08,832 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.30', 53301)发送回复：

Windows IP 配置


以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 本地连接* 11:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::c84d:500a:2b62:d8a7%14
   IPv4 地址 . . . . . . . . . . . . : 192.168.152.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::9860:7c4:58bb:99be%18
   IPv4 地址 . . . . . . . . . . . . : 192.168.157.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::28af:2f50:18fd:407%10
   IPv4 地址 . . . . . . . . . . . . : 192.168.43.30
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.43.1

2021-08-03 18:03:08,795 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 18:03:08,795 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:353] - INFO: 成功开启流量代理服务器:('192.168.43.30', 22222)
等待客户端连接...
2021-08-03 18:03:21,637 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 18:07:51,155 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53717)连接失败
2021-08-03 18:07:54,832 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53722)连接失败
2021-08-03 18:08:09,223 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53736)连接失败
2021-08-03 18:08:23,031 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53746)连接失败
2021-08-03 18:08:41,907 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.59', 53758)与服务器连接成功
2021-08-03 18:08:41,907 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 18:09:37,595 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:284] - INFO: 正在请求：('192.168.43.59', 53758)请求目的ip:('192.168.43.30', 11111)
2021-08-03 18:09:37,595 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:54] - INFO: 请求成功：('192.168.43.59', 53758)正在与('192.168.43.30', 11111)通讯...

2021-08-03 18:13:50,737 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53904)连接失败
2021-08-03 18:13:53,949 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53908)连接失败
2021-08-03 18:13:57,834 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53913)连接失败
2021-08-03 18:13:59,685 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53917)连接失败
2021-08-03 18:14:01,328 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53920)连接失败
2021-08-03 18:14:02,909 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53924)连接失败
2021-08-03 18:14:04,518 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 53928)连接失败
2021-08-03 18:14:06,102 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.59', 53931)与服务器连接成功
2021-08-03 18:14:06,112 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 18:14:33,581 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.30', 53576)与服务器连接成功
2021-08-03 18:14:33,581 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 18:15:34,524 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:284] - INFO: 正在请求：('192.168.43.59', 53931)请求目的ip:('192.168.43.30', 11111)
2021-08-03 18:15:34,524 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:54] - INFO: 请求成功：('192.168.43.59', 53931)正在与('192.168.43.30', 11111)通讯...

2021-08-03 18:17:08,199 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 53931)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:17:08,267 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 53931)的回复

2021-08-03 18:17:08,267 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 53931)发送回复：

2021-08-03 18:17:21,546 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 53931)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:17:21,576 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 53931)的回复

2021-08-03 18:17:21,576 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 53931)发送回复：

2021-08-03 18:17:30,853 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 53931)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:17:31,001 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 53931)的回复

2021-08-03 18:17:31,001 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 53931)发送回复：

2021-08-03 18:21:58,025 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 54175)连接失败
2021-08-03 18:22:14,360 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.59', 54187)与服务器连接成功
2021-08-03 18:22:14,360 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 18:23:00,101 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:284] - INFO: 正在请求：('192.168.43.59', 54187)请求目的ip:('192.168.43.30', 11111)
2021-08-03 18:23:00,101 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:54] - INFO: 请求成功：('192.168.43.59', 54187)正在与('192.168.43.30', 11111)通讯...

2021-08-03 18:23:23,358 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54187)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:23:23,456 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54187)的回复

2021-08-03 18:23:23,457 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54187)发送回复：

2021-08-03 18:24:49,811 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 54270)连接失败
2021-08-03 18:25:04,671 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.59', 54285)与服务器连接成功
2021-08-03 18:25:04,671 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 18:25:25,916 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:284] - INFO: 正在请求：('192.168.43.59', 54285)请求目的ip:('192.168.43.30', 11111)
2021-08-03 18:25:25,916 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:54] - INFO: 请求成功：('192.168.43.59', 54285)正在与('192.168.43.30', 11111)通讯...

2021-08-03 18:25:41,784 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:25:41,888 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:25:41,888 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:26:39,119 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:26:39,148 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:26:39,148 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:28:10,113 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:28:10,198 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:28:10,198 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:29:37,536 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:29:37,609 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:29:37,610 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:30:21,572 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:32:25,758 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:32:25,758 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:32:25,758 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:32:25,792 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:32:25,792 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:35:10,572 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:35:11,034 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:35:11,034 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:36:20,201 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:36:20,232 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:36:20,232 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:36:31,224 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:36:31,249 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:36:31,249 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:36:33,681 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:36:33,714 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:36:33,714 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:36:34,773 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:36:34,799 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:36:34,799 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:36:36,085 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:36:36,117 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:36:36,117 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:36:37,363 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:36:37,391 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:36:37,391 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:39:08,839 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:317] - INFO: ('192.168.43.59', 54285)正在给('192.168.43.30', 11111)发送信息
2021-08-03 18:39:09,027 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:321] - INFO: 已收到('192.168.43.30', 11111)给('192.168.43.59', 54285)的回复

2021-08-03 18:39:09,027 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:326] - INFO: 成功给('192.168.43.59', 54285)发送回复：

2021-08-03 18:40:13,635 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 55025)连接失败
2021-08-03 18:40:34,010 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 55039)连接失败
2021-08-03 18:41:07,023 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 55061)连接失败
2021-08-03 18:41:41,032 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 55081)连接失败
2021-08-03 18:41:44,623 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:241] - WARNING: 客户端：('192.168.43.59', 55086)连接失败
2021-08-03 19:34:57,030 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 19:34:57,059 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:352] - INFO: 成功开启流量代理服务器:('192.168.43.30', 22222)
等待客户端连接...
2021-08-03 19:35:05,706 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 19:35:19,286 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 19:35:21,921 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:113] - INFO: 客户端：('192.168.43.30', 55367)与服务器连接成功
2021-08-03 19:35:21,922 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:138] - INFO: 用户liu登陆成功！
2021-08-03 19:35:55,368 - H:\python3.8.2\lib\asyncio\base_events.py[line:1707] - ERROR: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<handle_echo() done, defined at H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py:237> exception=OSError(22, '信号灯超时时间已到', None, 121, None)>
Traceback (most recent call last):
  File "H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py", line 276, in handle_echo
    l_reader, l_writer = await asyncio.open_connection(dst_ip, dst_port)
  File "H:\python3.8.2\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "H:\python3.8.2\lib\asyncio\base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "H:\python3.8.2\lib\asyncio\base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "H:\python3.8.2\lib\asyncio\base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "H:\python3.8.2\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "H:\python3.8.2\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "H:\python3.8.2\lib\asyncio\windows_events.py", line 595, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到
2021-08-03 20:05:37,098 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 20:05:41,426 - H:\python3.8.2\lib\asyncio\proactor_events.py[line:623] - DEBUG: Using proactor: IocpProactor
2021-08-03 20:05:41,431 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:322] - INFO: 成功开启流量代理服务器:('192.168.43.30', 22222)
等待客户端连接...
2021-08-03 20:05:45,493 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:91] - INFO: 客户端：('192.168.43.30', 55532)与服务器连接成功
2021-08-03 20:05:45,493 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:116] - INFO: 用户liu登陆成功！
2021-08-03 20:05:55,658 - H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py[line:53] - INFO: 请求成功：('192.168.43.30', 55532)正在与('192.168.43.30', 11111)通讯...

2021-08-03 20:06:12,369 - H:\python3.8.2\lib\asyncio\base_events.py[line:1707] - ERROR: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<handle_echo() done, defined at H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py:215> exception=NameError("name 'server_addr' is not defined")>
Traceback (most recent call last):
  File "H:/pycharm/0pycharm_project/flow_agent_system_server/traffic_forwarding/server/server/TCP_echo_server.py", line 286, in handle_echo
    logging.info(str(client_addr) + '正在给' + str(server_addr) + '发送信息')
NameError: name 'server_addr' is not defined
